version: '3.8'

services:
  todoapp-api:
    build:
      context: .
      dockerfile: TodoApp.API/Dockerfile
    volumes:
      - ./TodoApp.API:/app/TodoApp.API
    ports:
      - "5089:8080"
    container_name: todoapp-api